### PR TITLE
Cc fetch file and test fix

### LINKED ISSUE #19: Fetch File
Create a fetch data file (allData.js) that will get all data, begin replacing the data with fetched data variables.

### PR DESCRIPTION
**Pull request by carlymclift**
### What’s this PR do?
* Fixes last test of the user class testing file to make use of the sample data and return whats expected
* create file for the fetch data (still needs to be imported to scripts.js when we are ready)

### Where should the reviewer start?
fetchAllData.js

### How should this be manually tested?
`npm test` for the user test file and user class 
fetch : n/a

resolves #19

### CODE REVIEW

File: src/fetchAllData.js [hunk 1]
```diff
@@ -0,0 +1,41 @@
+function fetchData() {
+  let userData = fetch('https://fe-apps.herokuapp.com/api/v1/fitlit/1908/users/userData')
+    .then(response => response.json())
+    .then(data => {
+      return data.userData;
+    })
+    .catch(err => console.log(err.message))
```
Comment (relyt4me) [inline src/fetchAllData.js:7]: We will want to do something more with these errors later but good catch thus far.

Comment (jordy1611) [reply src/fetchAllData.js:7]: I think console logging is a bit cleaner!
